sudo: false
language: node_js

cache:
  directories:
    - ~/.npm

node_js:
  - 10
  - 8

install: npm install

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release